### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by vismitap**
## Issue that this pull request solves

Closes: #391

## Types of changes
Updated README.md by adding
* Emojis
* Line spaces
* Headings to all sections

_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

## Screenshots
Please attach the screenshots of the changes made in case of change in user interface
image
image
image
image
image
image
image
image

### CODE REVIEW

**Comment by vismitap** [comment]
@rpotter12 Please review this PR. Also, I didn't find your whatsapp-play channel in the GSSoC server. Do you know when it will be available?

**Review by rpotter12 — CHANGES_REQUESTED** [review]
Hi @vismitap, Please update your branch. Your PR should have only your changes. And Please use the Previous Usage screenshot only.

**Comment by vismitap** [comment]
> Hi @vismitap, Please update your branch. Your PR should have only your changes. And Please use the Previous Usage screenshot only.

Yeah that's because I switched to develop branch. If I again switch to master, only my commit will be there.

**Comment by rpotter12** [comment]
> > Hi @vismitap, Please update your branch. Your PR should have only your changes. And Please use the Previous Usage screenshot only.
> 
> Yeah that's because I switched to develop branch. If I again switch to master, only my commit will be there.
> Should I switch to the master branch?

Update your branch with develop branch. This will solve your issue.

**Pull request closed without merging**
